/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practice;

/**
 *
 * @author Wein
 */
public class CharacterPicking extends javax.swing.JFrame {

    /**
     * Creates new form CharacterPicking
     */
    public CharacterPicking() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChar1 = new javax.swing.JButton();
        btnChar2 = new javax.swing.JButton();
        btnChar3 = new javax.swing.JButton();
        btnChar4 = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        lblPlayer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnChar1.setText("Brett");
        btnChar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChar1ActionPerformed(evt);
            }
        });

        btnChar2.setText("Gabe");
        btnChar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChar2ActionPerformed(evt);
            }
        });

        btnChar3.setText("Migantron");
        btnChar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChar3ActionPerformed(evt);
            }
        });

        btnChar4.setText("SirKhai");
        btnChar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChar4ActionPerformed(evt);
            }
        });

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        lblPlayer.setText("Player 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btnChar1)
                        .addGap(55, 55, 55)
                        .addComponent(btnChar2)
                        .addGap(67, 67, 67)
                        .addComponent(btnChar3)
                        .addGap(58, 58, 58)
                        .addComponent(btnChar4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfirm))))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblPlayer)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChar1)
                    .addComponent(btnChar2)
                    .addComponent(btnChar3)
                    .addComponent(btnChar4))
                .addGap(60, 60, 60)
                .addComponent(btnConfirm)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int character1=0;
    int character2=0;
    int confirm=0;
    private void btnChar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChar1ActionPerformed
        // TODO add your handling code here:
        if(confirm==0){
            character1=1;
            btnChar1.setEnabled(false);
            btnChar2.setEnabled(true);
            btnChar3.setEnabled(true);
            btnChar4.setEnabled(true);
        }else if(confirm==1){
            character2=1;
            btnChar1.setEnabled(false);
            btnChar2.setEnabled(true);
            btnChar3.setEnabled(true);
            btnChar4.setEnabled(true);
        }
    }//GEN-LAST:event_btnChar1ActionPerformed

    private void btnChar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChar2ActionPerformed
        // TODO add your handling code here:
        if(confirm==0){
            character1=2;
            btnChar2.setEnabled(false);
            btnChar1.setEnabled(true);       
            btnChar3.setEnabled(true);
            btnChar4.setEnabled(true);
        }else if(confirm==1){
            character2=2;
            btnChar2.setEnabled(false);
            btnChar1.setEnabled(true);       
            btnChar3.setEnabled(true);
            btnChar4.setEnabled(true);
        }
    }//GEN-LAST:event_btnChar2ActionPerformed

    private void btnChar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChar3ActionPerformed
        // TODO add your handling code here:
        if(confirm==0){
            character1=3;
            btnChar2.setEnabled(true);
            btnChar1.setEnabled(true);       
            btnChar3.setEnabled(false);
            btnChar4.setEnabled(true);
        }else if(confirm==1){
            character2=3;
            btnChar2.setEnabled(true);
            btnChar1.setEnabled(true);       
            btnChar3.setEnabled(false);
            btnChar4.setEnabled(true);
        }
    }//GEN-LAST:event_btnChar3ActionPerformed

    private void btnChar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChar4ActionPerformed
        // TODO add your handling code here:
        if(confirm==0){
            character1=4;
            btnChar4.setEnabled(false);
            btnChar2.setEnabled(true);
            btnChar1.setEnabled(true);       
            btnChar3.setEnabled(true);
        }else if(confirm==1){
            character2=4;
             btnChar4.setEnabled(false);
            btnChar2.setEnabled(true);
            btnChar1.setEnabled(true);       
            btnChar3.setEnabled(true);
        }
    }//GEN-LAST:event_btnChar4ActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        lblPlayer.setText("Player 2");
        confirm++;
        if(confirm==2){
            new pvp(character1,character2).setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharacterPicking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharacterPicking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharacterPicking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharacterPicking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterPicking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChar1;
    private javax.swing.JButton btnChar2;
    private javax.swing.JButton btnChar3;
    private javax.swing.JButton btnChar4;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel lblPlayer;
    // End of variables declaration//GEN-END:variables
}
